# Generated by Django 4.2.16 on 2024-09-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='index.jpg', upload_to='')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=1500)),
                ('Director', models.CharField(max_length=150)),
                ('Four_main_actors', models.CharField(max_length=250)),
                ('year_release', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
