# Generated by Django 4.2.16 on 2024-09-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default='media/index.jpg', upload_to=''),
        ),
    ]
