# Generated by Django 4.2.16 on 2024-09-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_reviews_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, default='index.jpg', upload_to='', width_field=200),
        ),
    ]
