# Generated by Django 4.2.16 on 2024-09-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movies_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, default='index.jpg', upload_to=''),
        ),
    ]
